; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27027.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG213068 DB	'd:\qt\5.9\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+15
$SG213069 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG213070 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG213363 DB	'd:\qt\5.9\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+15
$SG213364 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG213365 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_MainWindow
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	000000000000006bH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000063H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	000000000000004cH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000039H
	DB	04dH
	DB	061H
	DB	069H
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	067H
	DB	065H
	DB	074H
	DB	04aH
	DB	073H
	DB	06fH
	DB	06eH
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	04eH
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	DB	00H
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	00H
	DB	06fH
	DB	075H
	DB	072H
	DB	043H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	00H
	ORG $+4
	ORG $+8
?qt_meta_data_MainWindow@@3QBIB DD 07H			; qt_meta_data_MainWindow
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	018H
	DD	02H
	DD	0aH
	DD	04H
	DD	00H
	DD	01bH
	DD	02H
	DD	0aH
	DD	02bH
	DD	0aH
	DD	03H
	DD	02bH
	DD	00H
	ORG $+4
$SG212773 DB	'd:\qt\5.9\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+7
$SG212774 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG212775 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ	; MainWindow::metaObject
PUBLIC	?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z		; MainWindow::qt_metacast
PUBLIC	?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_metacall
PUBLIC	?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
PUBLIC	?staticMetaObject@MainWindow@@2UQMetaObject@@B	; MainWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?getJsonFileName@MainWindow@@QEAAXAEBVQString@@@Z:PROC ; MainWindow::getJsonFileName
EXTRN	?ourConnect@MainWindow@@QEAAXXZ:PROC		; MainWindow::ourConnect
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@MainWindow@@2UQMetaObject@@B DB 030H DUP (?) ; MainWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+109
	DD	imagerel $unwind$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@MainWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@MainWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'MainWindow::staticMetaObject'', COMDAT
; File d:\qtworks\test\x64\debug\moc\moc_mainwindow.cpp
; Line 84
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+8, rax
; Line 85
	lea	rax, OFFSET FLAT:?qt_meta_data_MainWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'MainWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; MainWindow::qt_static_metacall
; File d:\qtworks\test\x64\debug\moc\moc_mainwindow.cpp
; Line 71
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 72
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 73
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 75
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN5@qt_static_:
; Line 76
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?getJsonFileName@MainWindow@@QEAAXAEBVQString@@@Z ; MainWindow::getJsonFileName
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 77
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?ourConnect@MainWindow@@QEAAXXZ		; MainWindow::ourConnect
$LN7@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 81
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; MainWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; MainWindow::qt_metacall
; File d:\qtworks\test\x64\debug\moc\moc_mainwindow.cpp
; Line 103
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 104
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 105
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 106
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 107
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 108
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 109
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 110
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 111
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 112
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 113
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 114
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 116
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 117
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; MainWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z PROC		; MainWindow::qt_metacast
; File d:\qtworks\test\x64\debug\moc\moc_mainwindow.cpp
; Line 95
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 96
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 97
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 98
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 99
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 100
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z ENDP		; MainWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ PROC	; MainWindow::metaObject
; File d:\qtworks\test\x64\debug\moc\moc_mainwindow.cpp
; Line 90
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 91
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@MainWindow@@2UQMetaObject@@B ; MainWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 92
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; MainWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\5.9\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtworks\test\x64\debug\moc\moc_mainwindow.cpp
; Line 120
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtworks\test\x64\debug\moc\moc_mainwindow.cpp
; Line 120
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
